### ISSUE TITLE
[opentelemetry-php-contrib] SdkBundle: OTLP exporter factory creates exporter with default values

### ISSUE THREAD

**Issue by DrLuke** [open-telemetry/opentelemetry-php#1146]
**Describe your environment** Describe any aspect of your environment relevant to the problem, including your php version (`php -v` will tell you your current version), version numbers of installed dependencies, information about your cloud hosting provider, etc. If you're reporting a problem with a specific version of a library in this repo, please check whether the problem has been fixed on master.

Tried on both 
```
      "open-telemetry/sdk": "1.0.0",
      "open-telemetry/symfony-sdk-bundle": "0.0.23",
```
and
```
      "open-telemetry/sdk": "dev-main",
      "open-telemetry/symfony-sdk-bundle": "dev-main",
```

**Steps to reproduce**
With the config:
```yaml
otel_sdk:
    trace:
        enabled: true
        span:
          processors: simple
        exporters:
          - "otlp+grpc://otel-col:4317"
          - "otlp+http://otel-col:4318"
```

The OTLP span exporters are created with default values for [`protocol`](https://github.com/open-telemetry/opentelemetry-php/blob/main/src/Contrib/Otlp/SpanExporterFactory.php#L59) and [`endpoint`](https://github.com/open-telemetry/opentelemetry-php/blob/main/src/Contrib/Otlp/SpanExporterFactory.php#L66) instead of the values defined in the config.

I guess the SdkBundle is not setting the values in the config the factory is trying to access.

**What is the expected behavior?**
Exporters configured as I specified

**What is the actual behavior?**
Exporters configured with default values
