### ISSUE TITLE
OpenTelemetry Laravel with Zipkin not creating auto spans

### ISSUE THREAD

**Issue by de3** [open-telemetry/opentelemetry-php#1241]
**Issue Description:**

I'm encountering an issue where OpenTelemetry Laravel is not generating auto spans when using Zipkin as the exporter. I've followed the official documentation (https://opentelemetry.io/docs/languages/php/automatic/) for Laravel instrumentation and configured the Zipkin exporter correctly.

Environment:

- PHP version: 8.3.3
- Laravel version: 8
- Instrumentation Libraries: https://packagist.org/packages/open-telemetry/opentelemetry-auto-laravel
- Exporter: https://packagist.org/packages/open-telemetry/exporter-zipkin

Environment Variables:

- OTEL_PHP_AUTOLOAD_ENABLED=true
- OTEL_SERVICE_NAME=fooobar
- OTEL_TRACES_EXPORTER=zipkin
- OTEL_PROPAGATORS=baggage,tracecontext
- OTEL_EXPORTER_ZIPKIN_ENDPOINT=http://zipkin:9411

Troubleshooting Steps Taken:

- Testing with exporter `console`, no issue, tracer shown in console
- Zipkin endpoint is reachable, trying to modify endpoint to random port, it return error (Failed to connect to zipkin port 9412), I assume existing config is correct
- When add manual span in a controller, it return my custom span including automatic span
- When there is no manual span (custom span) in controller, there is no span generated in zipkin

Expected Result:

Automatic spans are generated even there is no manual span in controller

Actual Result:

No automatic spans are created when there is no manual span in controller

**Comment by ChrisLightfootWild** [comment]
I have used this locally with Zipkin before. I will have a look at this and see if it is still working as expected!

@de3 how are you running your application?

**Comment by de3** [comment]
Hi @ChrisLightfootWild 

So I add opentelemetry to my existing laravel application using automatic instrumentation and [zero code configuration](https://opentelemetry.io/docs/languages/php/automatic/#zero-code-configuration-for-automatic-instrumentation) 
I use [laravel instrument libraries](https://packagist.org/packages/open-telemetry/opentelemetry-auto-laravel) and [zipkin exporter](https://packagist.org/packages/open-telemetry/exporter-zipkin) as tracer exporter
My laravel stack and zipkin are running inside docker

I assume when using automatic instrumentation it will create [span automatically](https://github.com/opentelemetry-php/contrib-auto-laravel?tab=readme-ov-file#overview) whenever I access my application 

So I try to access 1 on my API endpoint, but don't see any span created in zipkin dashboard

When I try to create manual span, somehow it showing including others span that I not create manually

Do you need another details to replicate @ChrisLightfootWild ?

**Comment by ChrisLightfootWild** [comment]
@de3 I've just tested with PHP 8.3.3 and had the following locally:

![image](https://github.com/open-telemetry/opentelemetry-php/assets/106102472/699cfedb-169b-4484-8598-79515174645d)

Here's a snippet of my docker-compose:
```yaml
    command:
    - php
    - artisan
    - serve
    - --host
    - 0.0.0.0
    - -vvv
    environment:
      OTEL_EXPORTER_ZIPKIN_ENDPOINT: http://zipkin:9411/api/v2/spans
      OTEL_PHP_AUTOLOAD_ENABLED: "true"
      OTEL_PROPAGATORS: baggage,tracecontext
      OTEL_SERVICE_NAME: laravel-app-10.x
      OTEL_TRACES_EXPORTER: zipkin

```

How are you running PHP in your container? I wonder if there might be a difference there.
