### ISSUE TITLE
Incomplete documentation when using auto-instrumentation (Symfony)

### ISSUE THREAD

**Issue by dkarlovi** [open-telemetry/opentelemetry-php#1255]
**Describe your environment** 

```
open-telemetry/api                        1.0.3       API for OpenTelemetry PHP.
open-telemetry/context                    1.0.2       Context implementation for OpenTelemetry PHP.
open-telemetry/exporter-otlp              1.0.4       OTLP exporter for OpenTelemetry.
open-telemetry/gen-otlp-protobuf          1.1.0       PHP protobuf files for communication with OpenTelemetry OTLP collectors/servers.
open-telemetry/opentelemetry-auto-symfony 1.0.0beta23 OpenTelemetry auto-instrumentation for Symfony
open-telemetry/sdk                        1.0.8       SDK for OpenTelemetry PHP.
open-telemetry/sem-conv                   1.24.0      Semantic conventions for OpenTelemetry PHP.
```

**Steps to reproduce**

1. install `open-telemetry/opentelemetry-auto-symfony`
2. try to export spans into the collector from an `\Symfony\Component\HttpKernel\KernelEvents::TERMINATE` event handler
3. ?

**What is the expected behavior?**

Being able to export the spans / metrics / logs according to the docs provided by the auto-instrumentation.

**What is the actual behavior?**

I was unable to bridge the gap of understanding how the spans created by auto-instrumentation get to the exporter transport. I understand there's an exporter, transport, span processor, tracer, tracer provider (a lot of moving parts BTW), but it's not clear from docs or many examples I've looked what's the intended rest of the owl.

**Additional context**

I was a committer on this repo several years ago and have previously implemented OTEL on Symfony successfully before (probably the first dev to do so), but this have changed significantly in the meantime with the native extension etc. Any help appreciated! :smile:

**Comment by dkarlovi** [comment]
Nevermind, it's actually in the docs, but quite difficult to understand you need it.

Add this to your public/index.php or `Kernel::boot`

HTTP variant:

```php
\OpenTelemetry\API\Globals::registerInitializer(function (\OpenTelemetry\API\Instrumentation\Configurator $configurator) {
    $propagator = \OpenTelemetry\API\Trace\Propagation\TraceContextPropagator::getInstance();
    $exporter = new \OpenTelemetry\Contrib\Otlp\SpanExporter(
        (new \OpenTelemetry\Contrib\Otlp\OtlpHttpTransportFactory())->create('http://telemetry:4318/v1/traces', 'application/json')
    );
    $spanProcessor = new \OpenTelemetry\SDK\Trace\SpanProcessor\SimpleSpanProcessor($exporter);
    $tracerProvider = (new \OpenTelemetry\SDK\Trace\TracerProviderBuilder())
        ->addSpanProcessor($spanProcessor)
        ->build();

    return $configurator
        ->withTracerProvider($tracerProvider)
        ->withPropagator($propagator);
});
```

gRPC variant:

```php
        \OpenTelemetry\API\Globals::registerInitializer(function (\OpenTelemetry\API\Instrumentation\Configurator $configurator) {
            $propagator = \OpenTelemetry\API\Trace\Propagation\TraceContextPropagator::getInstance();

            $transport = (new \OpenTelemetry\Contrib\Grpc\GrpcTransportFactory())->create('http://telemetry:4317' . \OpenTelemetry\Contrib\Otlp\OtlpUtil::method(\OpenTelemetry\API\Signals::TRACE));
            $exporter = new \OpenTelemetry\Contrib\Otlp\SpanExporter($transport);
            $spanProcessor = new \OpenTelemetry\SDK\Trace\SpanProcessor\SimpleSpanProcessor($exporter);
            $tracerProvider = (new \OpenTelemetry\SDK\Trace\TracerProviderBuilder())
                ->addSpanProcessor($spanProcessor)
                ->build();

            return $configurator
                ->withTracerProvider($tracerProvider)
                ->withPropagator($propagator);
        });
```

**Comment by dkarlovi** [comment]
Example with exporting from Symfony kernel

```php
# add to App\Kernel

    public function boot(): void
    {
        parent::boot();

        $container = $this->container;
        \OpenTelemetry\API\Globals::registerInitializer(function (Configurator $configurator) use ($container): Configurator {
            return $configurator
                ->withTracerProvider($container->get(\OpenTelemetry\API\Trace\TracerProviderInterface::class))
                ->withPropagator($container->get(\OpenTelemetry\Context\Propagation\TextMapPropagatorInterface::class));
        });
    }
```

```yaml
# config/packages/opentelemetry.yaml
services:
    _defaults:
        autowire: true
        autoconfigure: true

    OpenTelemetry\Context\Propagation\TextMapPropagatorInterface:
        factory: ['OpenTelemetry\API\Trace\Propagation\TraceContextPropagator', 'getInstance']
        public: true # needed because we request this service from Kernel::boot() method

    OpenTelemetry\SDK\Trace\TracerProviderBuilder:
        calls:
            - ['addSpanProcessor', ['@OpenTelemetry\SDK\Trace\SpanProcessorInterface']]
    OpenTelemetry\API\Trace\TracerProviderInterface:
        factory: ['@OpenTelemetry\SDK\Trace\TracerProviderBuilder', 'build']
        shared: true
        public: true # needed because we request this service from Kernel::boot() method

    OpenTelemetry\SDK\Trace\SpanProcessorInterface:
        alias: OpenTelemetry\SDK\Trace\SpanProcessor\SimpleSpanProcessor
    OpenTelemetry\SDK\Trace\SpanProcessor\SimpleSpanProcessor:

    OpenTelemetry\SDK\Trace\SpanExporterInterface: '@OpenTelemetry\Contrib\Otlp\SpanExporter'
    OpenTelemetry\Contrib\Otlp\SpanExporter: ~

    OpenTelemetry\Contrib\Grpc\GrpcTransportFactory: ~
    OpenTelemetry\SDK\Common\Export\TransportInterface:
        factory: ['@OpenTelemetry\Contrib\Grpc\GrpcTransportFactory', 'create']
        arguments: ['http://telemetry:4317/opentelemetry.proto.collector.trace.v1.TraceService/Export']
```
