### ISSUE TITLE
Default timeout for grpc transport is zero

### ISSUE THREAD

**Issue by devnev** [open-telemetry/opentelemetry-php#1449]
Versions:

        "php": ">=8.3",
        "open-telemetry/exporter-otlp": "^1.1",
        "open-telemetry/opentelemetry-auto-guzzle": "^1.0.1",
        "open-telemetry/opentelemetry-auto-http-async": "^1.0.1",
        "open-telemetry/opentelemetry-auto-io": "^0.0.12",
        "open-telemetry/opentelemetry-auto-psr18": "^1.0.4",
        "open-telemetry/transport-grpc": "^1.1",

I just update + bumped all of those so the lock versions match.

This is reproducable running in docker and running in kubernetes.

**Steps to reproduce**

Create a PHP application that uses opentelemetry

In a docker compose, run a collector with

```
services:
  collector:
    image: otel/opentelemetry-collector-contrib
  my-app:
    build: ...
    env:
      OTEL_EXPORTER_OTLP_ENDPOINT: http://collector:4317
      OTEL_EXPORTER_OTLP_PROTOCOL: grpc
      OTEL_TRACES_EXPORTER: otlp
```

Run this and trigger spans to be exported. 

**What is the expected behavior?**

Traces are exported to the collector

**What is the actual behavior?**

The exports fail with Deadline Exceeded.

**Additional context**

The cause for this is in `SpanExporterFactory`. The `getTimeout` methods checks environment variables, assigning the result to `$value`. However if the environment variables are unset, `$value` will be null. It then returns `$value/1000`, which coerces the `null` to `0`, returning a timeout of `0`. This causes all grpc calls to fail.

This can be additionally confirmed (and mitigated) by setting the corresponding timeout environment variables, e.g. `OTEL_EXPORTER_OTLP_TIMEOUT: 10000`, in the compose, after which exports succeed.
