### ISSUE TITLE
Has anybody managed to get traces send to a Grafana Labs hosted Tempo instance?

### ISSUE THREAD

**Issue by TomHart** [open-telemetry/opentelemetry-php#1622]
I'm trying to get traces sent to a Grafana Labs Tempo instance, but whatever config I put has issues. This is the closest I've gotten after installing the `grpc` PHP extension

```
        environment:
            OTEL_PHP_AUTOLOAD_ENABLED: true
            OTEL_TRACES_EXPORTER: otlp
            OTEL_EXPORTER_OTLP_PROTOCOL: grpc
            OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: https://tempo-redacted.grafana.net:443/
            OTEL_EXPORTER_OTLP_HEADERS: "Authorization=Basic REDACTED"
```

But `GrpcTransport` fails with `Received http2 header with status: 405`

**Comment by smaddock** [comment]
We have it working but are just using HTTP/protobuf for now.

OTel PHP is just sending to a local OTel Collector though, and then the collector (actually Grafana Alloy) is forwarding to Tempo. OTel PHP to Alloy and Alloy to Tempo are both HTTP/protobuf connections.

**Comment by smaddock** [comment]
OTel PHP is just sending to a local OTel Collector though, and then the collector (actually Grafana Alloy) is forwarding to Tempo.

**Comment by smaddock** [comment]
OTel PHP to Alloy and Alloy to Tempo are both HTTP/protobuf connections

**Comment by TomHart** [comment]
For anyone else ending up here, after enabling the OpenTelemetry option (duh 🤦‍♂), this config worked!

```
        environment:
            OTEL_PHP_AUTOLOAD_ENABLED: true
            OTEL_SERVICE_NAME: my_service_name
            OTEL_TRACES_EXPORTER: otlp
            OTEL_METRICS_EXPORTER: otlp
            OTEL_LOGS_EXPORTER: otlp
            OTEL_PROPAGATORS: baggage,tracecontext
            OTEL_EXPORTER_OTLP_ENDPOINT: https://otlp-gateway-prod-gb-south-1.grafana.net/otlp
            OTEL_EXPORTER_OTLP_HEADERS: "Authorization=Basic REDACTED"
```
