### ISSUE TITLE
OpenTelemetry Exporter fail with : 400 Bad Request json: cannot unmarshal array into Go value of type map[string]json.RawMessage

### ISSUE THREAD

**Issue by shabicheng** [open-telemetry/opentelemetry-php#265]
When I use otlp exporter to send traces, nothing happened in collector, so I add some outputs in php otlp exporter and see the errors, can any guys fix this?

When I debug with the code, I find the environments OTEL_EXPORTER_OTLP_xxx does not work, can any guys fix this too?

**Describe your environment** 

Use latest OpenTelemetry Collector 0.21.0

**Steps to reproduce**

Collector config 

```
receivers:
 otlp:
  protocols:
   grpc:
   http:
exporters:
  logging:
    loglevel: info
    sampling_initial: 5
    sampling_thereafter: 200
  logging/detail:
    loglevel: debug

service:
  pipelines:
    metrics:
      receivers: [otlp]
      exporters: [logging]
      #exporters: [logging/detail]
    traces:
      receivers: [otlp]
      exporters: [logging/detail]
    logs:
      receivers: [otlp]
      exporters: [logging]
```

**What is the expected behavior?**
What did you expect to see?

**What is the actual behavior?**

```
Exporting Trace: f3b10a08ba894e9a84482e6112d84d03, Parent: None, Span: c54c4321cbefea5f
RequestExceptionInterface Client error: `POST http://127.0.0.1:55681/v1/trace` resulted in a `400 Bad Request` response:
{
  "code": 3,
  "message": "json: cannot unmarshal array into Go value of type map[string]json.RawMessage",
  "details" (truncated...)
 
Exporting Trace: f3b10a08ba894e9a84482e6112d84d03, Parent: None, Span: 3363d0ee2f616964
RequestExceptionInterface Client error: `POST http://127.0.0.1:55681/v1/trace` resulted in a `400 Bad Request` response:
{
  "code": 3,
  "message": "json: cannot unmarshal array into Go value of type map[string]json.RawMessage",
  "details" (truncated...)
 
OTLPExample complete!
```

**Additional context**

```
--- a/contrib/Otlp/Exporter.php
+++ b/contrib/Otlp/Exporter.php
@@ -122,8 +122,10 @@ class Exporter implements Trace\Exporter
             $request = new Request('POST', $this->endpointURL, $this->headers, $json);
             $response = $this->client->sendRequest($request);
         } catch (RequestExceptionInterface $e) {
+            echo sprintf(PHP_EOL . 'RequestExceptionInterface %s ', $e->getMessage());
             return Trace\Exporter::FAILED_NOT_RETRYABLE;
         } catch (NetworkExceptionInterface | ClientExceptionInterface $e) {
+            echo sprintf(PHP_EOL . 'NetworkExceptionInterface|ClientExceptionInterface %s ', $e->getMessage());
             return Trace\Exporter::FAILED_RETRYABLE;
         }
```
