### ISSUE TITLE
[opentelemetry-php-contrib] OtelSdkBundle: Could not build SpanExporter (otlphttp)

### ISSUE THREAD

**Issue by ibrambe** [open-telemetry/opentelemetry-php#605]
MacOS 12.2.1 
PHP 7.4.21
Symfony 5.4.6
guzzlehttp/guzzle ^7.4
open-telemetry/opentelemetry-php-contrib ^0.0.2
docker collector

```yaml
// config/packages/otel_sdk.yaml
otel_sdk:
    resource:
        attributes:
            service.name: "OtelBundle Demo app"
    trace:
        span:
            processors: simple
        exporters:
            dsn: otlphttp+http://0.0.0.0:4318/v1/traces
```

Initialization of the exporter fails, I could get my proof of concept working by changing it to this, but of course, this only works for otlphttp.

```php
// OpenTelemetry/Symfony/OtelSdkBundle/Factory/GenericFactoryTrait.php

private function doBuild(array $options = []): object
{
    putenv('OTEL_EXPORTER_OTLP_ENDPOINT=' . $options['url']);

    $exporter = new \OpenTelemetry\Contrib\OtlpHttp\Exporter(
        new \GuzzleHttp\Client(),
        new \GuzzleHttp\Psr7\HttpFactory(),
        new \GuzzleHttp\Psr7\HttpFactory()
    );

    return $exporter;
}
```

Also tried `OpenTelemetry\Contrib\OtlpHttp\Exporter::fromConnectionString`, but Psr17FactoryDiscovery does not work with Guzzle's HttpFactory.

**Comment by tidal** [comment]
@ibrambe 
Thank you for your bug report.
I will have a look into this. I'm currenty working on some refactoring for the bundle.

**Comment by tidal** [comment]
related: https://github.com/open-telemetry/opentelemetry-php/issues/451

**Comment by tidal** [comment]
related: https://github.com/open-telemetry/opentelemetry-php/issues/613

**Comment by tidal** [comment]
This is an issue, which will be fixed with the exporter refactoring (WIP).

However for now you can do the following as a workaround:

```yaml
// config/packages/otel_sdk.yaml
otel_sdk:
    resource:
        attributes:
            service.name: "OtelBundle Demo app"
    trace:
        span:
            processors: simple
        exporters:
            - type: otlphttp
```
If the endpoint URL for the collector is different to the default (`https://localhost:4318/v1/traces`),
you can set it via the `OTEL_EXPORTER_OTLP_ENDPOINT` Environment Variable.
Once https://github.com/open-telemetry/opentelemetry-php/issues/613 is implemeted, this will
be possible by providing the Environment Variable in the `.env`file.
