### ISSUE TITLE
HTTP OTLP Exporter is broken in 0.0.16

### ISSUE THREAD

**Issue by marcospassos** [open-telemetry/opentelemetry-php#868]
**Describe your environment**

After upgrading to v0.0.16 both the metric and span exported started receiving a bad request repose from the collector:

```
exemplar.spanId: parse span_id:invalid length for ID, error found in #10 
readSpan.traceId: parse trace_id:invalid length for ID,
```

**Comment by brettmc** [comment]
Hi @marcospassos thanks for the report. I'm not able to replicate your issue, can you provide more info?
I'm running `examples/traces/features/exporters/otlp_http.php` and exporting it to a collector (v0.66, which is the latest), which is our usual smoke test for checking compatibility with the collector. I don't see any errors in the collector logs.

**Comment by marcospassos** [comment]
Hi @brettmc!

This is the collector I'm using:

```yml
  otel:
    image: otel/opentelemetry-collector-contrib:0.60.0
    command: --config /etc/otel/config.yaml
    volumes:
      - './otel:/etc/otel'
    ports:
      - "4317:4317"
      - "4318:4318"
      - "8888:8888"
      - "8889:8889"
      - "13133:13133"
```

config.yaml
```yml
receivers:
  otlp:
    protocols:
      http:

exporters:
  jaeger:
    endpoint: jaeger:14250
    tls:
      insecure: true
  logging:
    loglevel: debug
  prometheus:
    endpoint: "0.0.0.0:8889"

processors:
  batch:

extensions:
  health_check:

service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, jaeger]
    metrics:
      receivers: [otlp]
      exporters: [logging, prometheus]

  telemetry:
    logs:
      level: "debug"
```

Let me know if you still can't reproduce the issue usinf this docker compose file.
