### ISSUE TITLE
Bring auto-instrumentation to OpenTelemetry K8s Operator

### ISSUE THREAD

**Issue by svrnm** [open-telemetry/opentelemetry-php#932]
**Is your feature request related to a problem?**

With auto instrumentation for PHP being a thing, there is an opportunity to bring it to applications running in K8s clusters via the otel k8s operator automatically.

**Describe the solution you'd like**
Similar to other languages it would be great to be able to turn on injection of auto instrumentation for PHP, e.g. create an Instrumentation resource that configures the auto instrumentation (copied from python):

```yaml
apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: demo-instrumentation
spec:
  exporter:
    endpoint: http://demo-collector:4318
  propagators:
    - tracecontext
    - baggage
  python:
    env:
      - name: OTEL_PHP_...
        value: ...
```

and add an annotation to deployments:

```yaml
instrumentation.opentelemetry.io/inject-php: "true"
```

This would require the creation of an init container, similar to the existing ones:

https://github.com/open-telemetry/opentelemetry-operator/tree/main/autoinstrumentation

and a instrumentation`php.go` at

https://github.com/open-telemetry/opentelemetry-operator/tree/main/pkg/instrumentation

cc @open-telemetry/operator-approvers 

**Additional context**
Existing injection for other languages: https://opentelemetry.io/docs/k8s-operator/automatic/
